version: '3.8'

services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    privileged: true
    user: root
    ports:
      - 9696:8080
      - 50000:50000
    container_name: jenkins
    volumes:
#      - /Users/sushantkumar/Desktop/blog/jenkins/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home